Fixed new WOApplication jvmOptions support. If your WOApplication task doesn't explicitly include a "jvmOptions" attribute, then the jvmOptions instance variable was left as its default null value, which would result in the @JVM_OPTIONS@ template being left in the [MacOS|MacOSServer|UNIX]ClassPath.txt files, causing .woa startup to fail with the error "Exception in thread "main" java.lang.NoClassDefFoundError: @JVM_OPTIONS@". Fixed by setting default value to an empty string.
git-svn-id: https://svn.objectstyle.org/repos/woproject/trunk@1139 930f2ab1-3212-0410-a8ea-d1eb4cc50a93